- OWSData/Models/StoredProcs/GetUserSession.cs
- OWSData/Models/Tables/OpenWorldServerContext.cs
- OWSData/Models/Tables/UserSessions.cs
- OWSData/Models/Tables/Users.cs
- OWSData/Repositories/Implementations/MSSQL/UsersRepository.cs
- OWSData/Repositories/Implementations/Postgres/UsersRepository.cs
- OWSData/Repositories/Interfaces/IUsersRepository.cs
- OWSPublicAPI/Controllers/UsersController.cs
- OWSPublicAPI/OWSPublicAPI.xml
- OWSPublicAPI/Requests/Users/GetUserRequest.cs
- OWSPublicAPI/appsettings.json
Morning Dart,
I completed a Get User api for OWS
Laythros
> Added api/GetUser/<userGuid> GET.

- OWSInstanceManagement/appsettings.json
Changed DBConnectionString to localhost and OpenWorldServer so it's consistent with the other configurations.
> Changed DBConnectionString to Correct Information

- OWSInstanceManagement/Properties/launchSettings.json
- OWSInstanceManagement/appsettings.json
- OWSPublicAPI/Properties/launchSettings.json
Added docker support for OWSPublicAPI & OWSInstanceManagement
> Added Docker Support

- Databases/MSSQL/Dockerfile
- Databases/MSSQL/entrypoint.sh
- Databases/MSSQL/initialization.sh
- Databases/MSSQL/setup.sql
- docker-compose.yml
Added MSSQL Docker Support With Automated Database Restore for the OpenWorldDatabase
> Added MSSQL Docker Support

- .gitignore
- Databases/MSSQL/initialization.sh
- Databases/MSSQL/setup.sql
- docker-compose.yml
Added Persistent Storage For MSSQL And ENV Variables For Production Editions
> Added Persistent Storage For MSSQL And ENV Variables

- .gitignore
- OWSInstanceManagement/appsettings.json
- OWSPublicAPI/appsettings.json
- docker-compose.yml
Added Docker support for RabbitMQ
> Added Docker support for RabbitMQ

- .gitignore
- OWSInstanceManagement/Startup.cs
- OWSPublicAPI/Startup.cs
- docker-compose.yml
Fixed DataProtection-Keys not being persistent
> Fixed DataProtection-Keys not being persistent

- docker-compose.yml
- rabbitmq.conf
Added configuration file rabbitmq.conf to rabbitmq
> Added configuration file rabbitmq.conf to rabbitmq

- docker-compose.yml
Fixed issue where MSSQL couldn't mount volumes in OSX
> Fixed issue where MSSQL couldn't mount volumes in OSX

- OWSInstanceManagement/Startup.cs
- OWSPublicAPI/Startup.cs
- OWSShared/Implementations/SwaggerSecurityRequirementsDocumentFilter.cs
Fixed issue with Swagger Authorize
> Fixed issue with Swagger Authorize

- src/OWSExternalLoginProviders/Implementations/EpicOnlineServicesLoginProvider.cs
- src/OWSExternalLoginProviders/Interfaces/IExternalLoginProvider.cs
- src/OWSExternalLoginProviders/Internal/ExternalLoginProvider.cs
Added CancellationToken For ExternalLoginProviders Tasks
> Added CancellationToken For ExternalLoginProviders Tasks

- README.md
- src/OWSBenchmarks/OWSBenchmarks.csproj
- src/OWSBenchmarks/ResponseBenchmarks.cs
- src/OWSCharacterPersistence/OWSCharacterPersistence.csproj
- src/OWSCharacterPersistence/Startup.cs
- src/OWSData/OWSData.csproj
- src/OWSExternalLoginProviders/OWSExternalLoginProviders.csproj
- src/OWSInstanceLauncher/OWSInstanceLauncher.csproj
- src/OWSInstanceManagement/OWSInstanceManagement.csproj
- src/OWSInstanceManagement/Startup.cs
- src/OWSPublicAPI/OWSPublicAPI.csproj
- src/OWSShared/OWSShared.csproj
- src/OWSStatus/OWSStatus.csproj
- src/OWSTests/OWSTests.csproj
- Updated and Removed Dependencies
- Fixed Missing ows.css missing
- Updated Readme Fresh Build
- Update .Net Version and Projects
> Updated and Removed Dependencies 

- src/OWSInstanceLauncher/appsettings.json
- src/docker-compose.override.linux.yml
An alternative to #26 that doesn't require changes to the host.
> Add host.docker.internal to linux docker-compose

- DOCKER-POTSGRES.md
- README.md
- src/.docker/postgres/Dockerfile
- src/.docker/postgres/setup.sql
- src/OWSData/Repositories/Implementations/Postgres/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/InstanceManagementRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/UsersRepository.cs
- src/OWSData/SQL/PostgreQueries.cs
- src/OWSShared/Extensions/CustomHealthCheck.cs
- src/OWSShared/OWSShared.csproj
Add Postgres Repositories and Queries
Add Healthcheck
Add Postgres Docker (Disabled by default)
Add Instructions to use Postgres
> Implement Postgres Backend

- src/OWSData/Repositories/Implementations/MSSQL/UsersRepository.cs
Replace call to RemoveUser with RemoveCharacter.
> fix(user): fix stored procedure reference

- DOCKER-POSTGRES.md
- src/OWSCharacterPersistence/Startup.cs
- src/OWSCharacterPersistence/appsettings.json
- src/OWSData/Models/StorageOptions.cs
- src/OWSInstanceManagement/Startup.cs
- src/OWSInstanceManagement/appsettings.json
- src/OWSPublicAPI/Startup.cs
- src/OWSPublicAPI/appsettings.json
- src/OWSShared/Extensions/CustomHealthCheck.cs
- src/docker-compose.yml
Add commented examples for Postgres in docker-compose.yml.
Simplify DOCKER-POSTGRES.md instructions.
Add new OWSDBBackend configuration option (mandatory).
Add OWSDBBackend check on repository loading.
> refactor(postgres): simplify postgres alternative

- src/OWSCharacterPersistence/Startup.cs
- src/OWSInstanceManagement/Startup.cs
- src/OWSPublicAPI/Startup.cs
- src/OWSShared/Extensions/CustomHealthCheck.cs
Move DBBackend check into switch statement, defaulting to MSSQL.
> refactor(postgres): improve db check

- src/.docker/postgres/setup.sql
Fix CleanUp Procedure.
Fix DebugLog Typo's.
> fix(sql): fix debug logging and cleanup

- DOCKER-MYSQL.md
- README.md
- src/.docker/mysql/Dockerfile
- src/.docker/mysql/setup.sql
- src/OWSCharacterPersistence/Startup.cs
- src/OWSData/OWSData.csproj
- src/OWSData/Repositories/Implementations/MySQL/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/MySQL/InstanceManagementRepository.cs
- src/OWSData/Repositories/Implementations/MySQL/UsersRepository.cs
- src/OWSData/SQL/MySQLQueries.cs
- src/OWSInstanceManagement/Startup.cs
- src/OWSPublicAPI/Startup.cs
- src/OWSShared/Extensions/CustomHealthCheck.cs
- src/OWSShared/OWSShared.csproj
- src/docker-compose.yml
Implement MySQL backend.
Implement MySQL CustomHealthCheck.
Add documention.
Add Docker implementation for MariaDB/MySQL.
> feat(mysql): implement mysql backend

- src/.env
- src/docker-compose.yml
- Added RabbitMQ Environment Variables
> Added RabbitMQ Environment Variables 

- Databases/MySQL/UpdateScripts/20220613UpdateFrom20220424to20220613.sql
- Databases/Postgres/UpdateScripts/20220613UpdateFrom20220424to20220613.sql
- src/OWSData/Repositories/Implementations/MSSQL/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/MySQL/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/MySQL/InstanceManagementRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/InstanceManagementRepository.cs
- src/OWSData/SQL/MySQLQueries.cs
- src/OWSData/SQL/PostgresQueries.cs
MySQL/Postgres need a Database update.
> fix(db): update postgres/mysql to feature compatible

- src/.docker/mysql/setup.sql
Add COALESCE to avoid a NULL Comparison issue,
> fix(mysql): fix joinmbymapname

- Databases/MSSQL/UpdateScripts/20220801UpdateFrom20220424to20220801.sql
- Databases/MySQL/UpdateScripts/20220801UpdateFrom20220424to20220801.sql
- Databases/Postgres/UpdateScripts/20220801UpdateFrom20220424to20220801.sql
Allow optional UUID on Customer creation.
Implement RemoveUser API.
> feat(uuid): add customer uuid as parameter

- src/docker-compose.yml
Added Named Volumes to make volumes persistent between docker compose guid's
> Added Named Volumes

- Databases/MySQL/UpdateScripts/20220424UpdateFrom20210829to20220424.sql
- Databases/MySQL/UpdateScripts/20220613UpdateFrom20220424to20220613.sql
- Databases/MySQL/UpdateScripts/20220801UpdateFrom20220424to20220801.sql
Implement compatibility suggestions from #63
> fix(mysql): improve mariadb version compatibility

- .gitignore
- src/OWSData/Repositories/Implementations/MSSQL/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/MySQL/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/CharactersRepository.cs
- src/OWSData/SQL/GenericQueries.cs
Refactor AddCharacterToMapInstanceByCharName from SQL SP/Functions to C#.
Add Rider files to .gitignore.
Implement GenericQueries.cs for queries that are consistent across all DB's.
> refactor(sql): move logic to c#

- plugins/OWSPluginUE5/OWSPlugin.uplugin
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSAbilityTask_PlayMontageWait.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSAbilityTask_WaitCastTime.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSAbilityTask_WaitTargetData.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSCharacterWithAbilities.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSGameplayAbilityTargetActor_P.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSGameplayAbilityTargetActor_Tr.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Private/OWSTask_RootMotionConstantForce.cpp
- plugins/OWSPluginUE5/Source/OWSPlugin/Public/OWSCharacterWithAbilities.h
Fixed errors for upgrade to 5.1.  There are still some warnings I am looking into (Enhanced Input), but this compiles and runs.
> Upgraded the UE5 OWS Plugin for 5.1 Release

- docs/_config.yml
- docs/getting-started/mssql.md
- docs/getting-started/mysql.md
- docs/getting-started/postgres.md
- docs/index.md
_config.yml repository added to allow for local generation testing.
> style(doc): fix formatting and links

- src/.docker/messaging.yml
- src/docker-compose.yml
- Set hostname for rabbitmq
- Set cluster to OWS2
- Created persistent volume
- Added Messaging Volume
> Docker Update

- src/OWSManagement/.dockerignore
- src/OWSManagement/Dockerfile
- src/OWSManagement/OWSManagement.csproj
> OWSManagement Docker Fix

- src/OWSManagement/OWSManagement.csproj
- src/OWSManagement/Program.cs
- src/OWSManagement/Startup.cs
- Removed Nullable
- Removed ImplicitUsings
> Remove new ImplicitUsings

- src/OWSManagement/Controllers/SystemController.cs
- src/OWSManagement/OWSManagement.xml
Add `/api/system/status` endpoint to OWS Management
> feat(status): add system status api to management

- src/OWSShared/InternalAPICalls/InternalAPICallsService.cs
- src/OWSShared/Objects/ServerLauncherHealthMonitoring.cs
- src/OWSShared/Objects/ServerLauncherMQListener.cs
Removed Newtonsoft.Json dependency
@Dartanlla This requires testing before merging to main.
> Removed Newtonsoft.Json dependency

- src/OWSData/Repositories/Implementations/Postgres/CharactersRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/GlobalDataRespository.cs
- src/OWSData/Repositories/Implementations/Postgres/InstanceManagementRepository.cs
- src/OWSData/Repositories/Implementations/Postgres/UsersRepository.cs
- Fixed the correct connection cast for latest Npgsql
- Fixed transaction connection not opening
> Fixed Postgres Connection Issue
